spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        slidingWindowSize: 5
        failureRateThreshold: 50